# configs/x264_x265.yml

experiment_name: "template_experiment"
output_path: "results"

source_videos:
  - path: "/app/data/aomctc/Debugging_1920x1080_30fps_8bit_420.y4m"
    name: "Debugging_1080p"
    resolution: "1920x1080"
    resolution_name: "1080p"
    bit_depth: 8
    chroma_subsampling: "4:2:0"
    frame_rate: 30

  #- name: "videotestsrc_smpte"
  #  type: "videotestsrc"
  #  resolution: "3840x2160"
  #  resolution_name: "4k"
  #  framerate: 30
  #  duration_in_sec: 5
  #  pattern: "smpte"
  #  bit_depth: 8
  #  chroma_subsampling: "4:2:0"

tasks:
  - codec: "libx265"
    crf_values: [10, 28, 51]
    preset: ["ultrafast", "superfast", "veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow", "placebo"]
    config_file: "configs/codecs/x265_settings.cfg"

  - codec: "libx264"
    crf_values: [10, 21, 51]
    preset: ["ultrafast", "superfast", "veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow", "placebo"]
    config_file: "configs/codecs/x264_settings.cfg"